# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoilerVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tvshow', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SpoilerVictims',
        ),
    ]
